export const INVALID_DATA_ERROR_CODE = 400;
export const UNAUTHORIZED_ERROR_CODE = 401;
export const FORBIDDEN_ERROR_CODE = 403;
export const NOT_FOUND_ERROR_CODE = 404;
export const DUPLICATE_ERROR_CODE = 409;
export const DEFAULT_ERROR_CODE = 500;
